### PR TITLE
refactor all handling of attached files

### PR DESCRIPTION
**Pull request by reduxionist**
Extract attachment processing from forms, views.staff, and management.command.get_email, and consolidate it into a unified lib module function.
Also refactor the affected components, most notably lib.send_templated_email, to make it easier (IMO) to reason about changes to them.
Add unit tests for attachments with UTF-8 filenames, and functional tests for submission of same, as well as ASCII versions, through the public ticket-form.
Remove unused Attachment method "get_upload_to".

### CODE REVIEW

**Comment by reduxionist** [comment]
This is directed towards issues #343, #376, #413, #439, and #456, but because the new tests were written for the refactored code, they do not specially address each issue with its own individual test-case as they would normally. Nonetheless, they attempt to cover the consolidated code path that they all now share. Also, this continues our progress on #444.

**Comment by pawelmarkowski** [comment]
@reduxionist To ensure data consistency my comment from #462  


Great, so I am waiting for your upgrade.

In my opinion there is some kind of bug. If queue.slug does not match matchobj = re.match(r".*[" + queue.slug + "-(?P\d+)]", subject) get_email will create new ticket even if received message was an update for other queue.

**Comment by reduxionist** [comment]
That would definitely be bad, but that section of ticket_from_message is not one I touched in the refactoring, so that brittleness in the parsing has been that way since commit 306d8bf in Feb 2013... Regardless, from having implemented @brunotikami's PR #385 for a client installation, I remember that it used RFC 2822's message-id header to provide a far more robust threading mechanism. There are three more PRs, including one of of yours, waiting to be reviewed after this one. Once those are done, however, and after get testing of this reply-handling in place first, then I can try rebasing that code back into shape again for consideration to merge...
Thanks for your help and patience! 🙇

**Comment by reduxionist** [comment]
Great, thanks @gwasser!

**Pull request merged**
