### PR TITLE
Cs translation

### PR DESCRIPTION
**Pull request by jachym**
Adds translation to Czech

### CODE REVIEW

**Comment by timthelion** [comment]
I left some comments here: https://github.com/django-helpdesk/django-helpdesk/issues/703#issuecomment-460075710

It seems you removed the fuzzy translations but didn't fix the typos yet.

**Comment by gwasser** [comment]
Thank you @jachym! Let me know when you fixed the typos and are ready to merge it.

**Comment by jachym** [comment]
Thanks @timthelion for double-check.
@gwasser should be cleaned (for) now.

**Comment by timthelion** [comment]
I think this can be merged now.

**Pull request merged**
