### PR TITLE
- issue #493: internal error 500 on save query

### PR DESCRIPTION
**Pull request by pprolancer**
https://github.com/django-helpdesk/django-helpdesk/issues/493
I have attached an screenshot on error we have here.
Test Environment:
python == python3.5.2
django == django1.9.7

### CODE REVIEW

**Comment by pawelmarkowski** [comment]
hi
python == python3.5.2
django == django1.10.7

same issue, can you fix it? :+1:

**Comment by pprolancer** [comment]
I have fixed this in this pull request. but the author of this project asked me to write some testcases for this pull request. but I hadn't enough time to do that.
to see the quick fixing take a look here: https://github.com/django-helpdesk/django-helpdesk/pull/494/commits/babc7586cf0fc63e66081d166d6c75bbe7b624ac

**Comment by gwasser** [comment]
@pawelmarkowski @pprolancer Thanks for the report! If you don't have time to write up some tests, I might be able to do it soon and merge in your changes afterward.

**Comment by gwasser** [comment]
I'm going to merge this and then commit some tests. Thanks!

**Pull request merged**
