### PR TITLE
Fix for 'NoneType' object has no attribute 'email'

### LINKED ISSUE #807: 'NoneType' object has no attribute 'email' while doing get_email.
**Describe the bug**
When fetching an email with a CC, receive the following error
```
AttributeError: 'NoneType' object has no attribute 'email'
  File "myapp/taskapp/celery.py", line 47, in support_fetch_email
    call_command('get_email')
  File "django/core/management/__init__.py", line 148, in call_command
    return command.execute(*args, **defaults)
  File "django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "helpdesk/management/commands/get_email.py", line 80, in handle
    process_email(quiet=quiet)
  File "helpdesk/management/commands/get_email.py", line 113, in process_email
    process_queue(q, logger=logger)
  File "helpdesk/management/commands/get_email.py", line 243, in process_queue
    ticket = ticket_from_message(message=full_message, queue=q, logger=logger)
  File "helpdesk/management/commands/get_email.py", line 554, in ticket_from_message
    if t.assigned_to.email != cc.email_address:
```

Same error msg as #622 but in a different place.

### PR DESCRIPTION
**Pull request by ilikerobots**
Fixes #807

### CODE REVIEW

**Comment by gwasser** [comment]
Thank you! Hmm, any thoughts why the tests fail on Python 2?

**Comment by ilikerobots** [comment]
Not sure, actually.  I tried in my own env and everything passes (see log below). It's odd though, the error is in the CC handling test which makes me think it might be legit.  However, the error seems to be involving date handling.  

```
(django-helpdesk) $ python2.7 --version
Python 2.7.17
(django-helpdesk) $ git branch 
  master
* patch-2
(django-helpdesk) $ python2.7  quicktest.py helpdesk
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.................................................................
----------------------------------------------------------------------
Ran 65 tests in 2.705s

OK
Destroying test database for alias 'default'...
```

**Comment by ilikerobots** [comment]
Hi, regarding the test failure, I don't think it has anything to do with the change in this PR.  
I triggered a build with just a text change and it fails in exactly the same way: https://travis-ci.org/github/ilikerobots/django-helpdesk

I think it's an issue with pytz, probably related to this: https://bugzilla.redhat.com/show_bug.cgi?id=1295709/  

I can't reproduce locally, but i'm on a debian based not rpm.

**Comment by ilikerobots** [comment]
I created a fix for the test failure here: https://github.com/django-helpdesk/django-helpdesk/pull/813

**Comment by gwasser** [comment]
Sounds good thanks!

**Pull request merged**
