### PR TITLE
Display only queues for the logged-in user

### PR DESCRIPTION
**Pull request by jachym**
In the submission form (public and staff), display only queues, which should be available for the logged-in user only.

### CODE REVIEW

**Comment by jachym** [comment]
There is little change in the behaviour while creating ticket via e-mail.

Not sure, why Python 2 refuses :-/

**Comment by jachym** [comment]
@gwasser I'm moving to `development` branch. One issue I have: the logic moved to `forms.py`, I need to `__init__` method of `TicketForm` class

My problem is, that I create list of queues based on logged-in user. Not sure, how to get logged-in user in the `__init__` method (in `master` in `views/staff.py` this is part of the `request` object). Any hint?

**Comment by gwasser** [comment]
Hmm offhand not sure, will have to think about it. Possibly the right place is to look at where the form is generated in `views.py`, or maybe adapt the template that it is rendering.

**Comment by jachym** [comment]
See pull request for develop branch in pr #715

**Comment by gwasser** [comment]
Thank you! I merged #715. I hesitate to merge this change into the 0.2 release if it doesn't work well on both Python 2 and 3. So I'm going to suggest let's focus on getting 0.3 done :-)

**Comment by jachym** [comment]
This was addressed in the develop branch - closing.

**Pull request closed without merging**
