### PR TITLE
Fix Javascript typo

### PR DESCRIPTION
**Pull request by jrenaut**
This fix enables uploading new attachments to an existing ticket

### CODE REVIEW

**Comment by timthelion** [comment]
I'm having a lot of trouble understanding what is going on here. You have a javascript string that is built from a Django template bit...

This

```
$.get("{% url 'helpdesk:raw' "preset" %}?id=" + preset, function(data) {
```
should be rendered by django as

```
$.get("/raw/preset/?id=" + preset, function(data) {
```

by looking up `raw` in the URLS https://github.com/django-helpdesk/django-helpdesk/blob/3695cfa19dd860ab1b6f38486b5d1ff0ade3c52f/helpdesk/urls.py#L116

I think that your change breaks that behavior.

Did you test this change? What am I missing?

**Comment by jrenaut** [comment]
The line is missing the "+" before and after the variable "preset" so I'm just getting a Javascript error. I think the intention is to send whatever value is in preset to the Django url (ie if preset = "foo" then the url would be /raw/foo/?id=foo).

I tested it locally.

**Comment by timthelion** [comment]
That doesn't make sense for two reasons:

1. Why would `foo` be duplicated in the URL, just from that you should see that there is something wrong here.
2. More importantly, the stuff in the `{` curly brackets gets rendered server side before the javascript is run.

**Comment by jrenaut** [comment]
Ok, I think I see what's going on. It's in the document.ready function and there's no element with id "id_preset" - I think it's dead code with a typo in it so the #ShowFileUpload handler wasn't attaching and THAT'S why I couldn't upload a file. 

Below is a snippet of the rendered page on my local dev environment. My fix makes the Javascript valid but the function I "fixed" doesn't do anything. 

`   $(document).ready(function() {
      $("#ShowFurtherEditOptions").click(function() {
         $("#FurtherEditOptions").toggle();
         return false;
      });

      $("#ShowFileUpload").click(function() {
         $("#FileUpload").fadeIn();
         $("#ShowFileUploadPara").hide();
         return false;
      });

      $('#id_preset').change(function() {
         preset = $('#id_preset').val();
         if (preset != '') {
            $.get("{% url 'helpdesk:raw' " +
               preset + " %}?id=" + preset,
               function(data) {
                  $("#commentBox").val(data)
               });
         }
      });`

**Comment by gwasser** [comment]
Thank you! It could be dead code that got missed during our last HTML/JS overhaul, will need to investigate and see if it's safe to remove completely, but fixing it for now is definitely good!

**Comment by jrenaut** [comment]
Happy to help. I just started using Helpdesk recently for my business ([Cold Ants Properties](https://www.coldants.com)) and it's been enormously helpful. I'm a mediocre coder but looking forward to making some more substantive contributions.

**Comment by timthelion** [comment]
This should definitely not have been merged. Please rollback.

```
Traceback (most recent call last):
  File "/home/timothy/pu/auto-mat/klub/third-party/django-helpdesk/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/timothy/pu/auto-mat/klub/third-party/django-helpdesk/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/timothy/pu/auto-mat/klub/third-party/django-helpdesk/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/timothy/pu/auto-mat/klub/third-party/django-helpdesk/helpdesk/views/staff.py", line 393, in view_ticket
    'SHOW_SUBSCRIBE': show_subscribe,
  File "/home/timothy/pu/auto-mat/klub/third-party/django-helpdesk/lib/python3.7/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/timothy/pu/auto-mat/klub/third-party/django-helpdesk/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/timothy/pu/auto-mat/klub/third-party/django-helpdesk/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/timothy/pu/auto-mat/klub/third-party/django-helpdesk/lib/python3.7/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/timothy/pu/auto-mat/klub/third-party/django-helpdesk/lib/python3.7/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/timothy/pu/auto-mat/klub/third-party/django-helpdesk/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/timothy/pu/auto-mat/klub/third-party/django-helpdesk/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/timothy/pu/auto-mat/klub/third-party/django-helpdesk/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/timothy/pu/auto-mat/klub/third-party/django-helpdesk/lib/python3.7/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/timothy/pu/auto-mat/klub/third-party/django-helpdesk/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/timothy/pu/auto-mat/klub/third-party/django-helpdesk/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/timothy/pu/auto-mat/klub/third-party/django-helpdesk/lib/python3.7/site-packages/django/template/defaulttags.py", line 516, in render
    return self.nodelist.render(context)
  File "/home/timothy/pu/auto-mat/klub/third-party/django-helpdesk/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/timothy/pu/auto-mat/klub/third-party/django-helpdesk/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/timothy/pu/auto-mat/klub/third-party/django-helpdesk/lib/python3.7/site-packages/django/template/defaulttags.py", line 516, in render
    return self.nodelist.render(context)
  File "/home/timothy/pu/auto-mat/klub/third-party/django-helpdesk/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/timothy/pu/auto-mat/klub/third-party/django-helpdesk/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/timothy/pu/auto-mat/klub/third-party/django-helpdesk/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/timothy/pu/auto-mat/klub/third-party/django-helpdesk/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/timothy/pu/auto-mat/klub/third-party/django-helpdesk/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/timothy/pu/auto-mat/klub/third-party/django-helpdesk/lib/python3.7/site-packages/django/template/defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/timothy/pu/auto-mat/klub/third-party/django-helpdesk/lib/python3.7/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/timothy/pu/auto-mat/klub/third-party/django-helpdesk/lib/python3.7/site-packages/django/urls/resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'raw' with arguments '(' + preset + ',)' not found. 1 pattern(s) tried: ['raw/(?P<type>\\w+)/$']
```

**Comment by timthelion** [comment]
The branch name `patch-1` suggests to me that this was done in the github editor and never even tested, as that is the default branch name in the editor.

**Comment by Benbb96** [comment]
@gwasser I just tested this and it gives me the following error on a ticket page : 

    NoReverseMatch at /tickets/1/
    Reverse for 'raw' with arguments '(' + preset + ',)' not found. 1 pattern(s) tried: ['raw/(?P<type>\\w+)/$']

**Comment by timthelion** [comment]
I've created a PR to roll this back https://github.com/django-helpdesk/django-helpdesk/pull/990 I also changed the quote style so it is less likely to look like a bug.

**Comment by jrenaut** [comment]
I'm sorry for the hassle. Yes, it was done in the Github editor, but just because my fork has a few other small changes not worthy of being merged in. I *DID* test it locally, I'm not sure what happened with the patch.

**Comment by timthelion** [comment]
You can use an interactive tool to pick and choose changes. I use magit which is part of emacs(or spacemacs in my case). But it's not exactly designed for mortals. If you want to do clicky stuff, I believe github has one that runs on windows and mac.

**Comment by gwasser** [comment]
No worries @jrenaut it seemed like a simple fix! Javascript is a little silly sometimes. I didn't catch it either, and our automated testing apparently isn't testing the javascript either, something to work on for better future testing.

**Pull request merged**
