### PR TITLE
Remove Python 2 dependency and Add Script for Pypi release

### PR DESCRIPTION
**Pull request by uhurusurfa**
Support for deplying a release tag to PyPi automatically
REove the six package and the code that used it to maintain Python 2 compqtibility

### CODE REVIEW

**Comment by martin-marty** [comment]
Is there no [Private PyPi](https://pypi.org/project/private-pypi/) configuration for local testing before pushing?

**Comment by martin-marty** [comment]
How urgent is this please @uhurusurfa ? I've very little time available at the moment, if it's a high priority, I can at the very least create a check list of todo's in order to implement this. If you can wait until the weekend, I can try to find the time to implement what's required in order to cover this.

**Comment by uhurusurfa** [comment]
> How urgent is this please @uhurusurfa ? I've very little time available at the moment, if it's a high priority, I can at the very least create a check list of todo's in order to implement this. If you can wait until the weekend, I can try to find the time to implement what's required in order to cover this.

@martin-marty - I have no vested interest in checking it on a separate repository as the effort just doesnot warrant  it in my opinion but if you want to invest your time in it please go ahead. If it does not work then there is no issue. If it does the wrong thing there is always the manual process to unwind it quickly and/or publish it correctly.

**Comment by martin-marty** [comment]
Good morning @uhurusurfa - I've ran into issues with private-pypi so haven't been able to implement a local pypi server (there's a dependency issue :
```
$ pip install redis-server
ERROR: Could not find a version that satisfies the requirement redis-server (from versions: none)
ERROR: No matching distribution found for redis-server
```
).
It looks good though apart from `helpdesk.views.staff` is missing a `time` import, it's used in `views.staff.get_due_date_from_request_or_ticket`.
I don't have write permission for this branch but it can be fixed by changing line 13:
`from datetime import datetime, timedelta` -> `from datetime import datetime, time, timedelta`

**Comment by uhurusurfa** [comment]
Thanks @martin-marty -  good catch.
Can you review and approve the PR please?

**Review by martin-marty — APPROVED** [review]
Looks good, approved as requested.

**Review by martin-marty — APPROVED** [review]
All good

**Review by martin-marty — APPROVED** [review]
All good

**Pull request merged**
