### PR TITLE
Iframe submit and other fixes

### PR DESCRIPTION
**Pull request by timthelion**
This cannot be merged. It seems that something weird happened with the merge from devel to master and a few commits got lost. I'll try to work on rebasing everything soon.

### CODE REVIEW

**Comment by gwasser** [comment]
Thanks! Can you give a summary of all the changes here?

**Comment by timthelion** [comment]
This is a major change. It is a complete redesign of the KB system. Rather than having every KB item on its own page, the KB items are shown inline on the KB category page. KB items are now associated with tickets, and you can filter tickets by KB item. Furthermore, kb category and ticket submission views can be embedded in iframes. When embedding the submission views, you can pre-fill fields including custom fields. This is documented in `integration.rst`. You can also hide fields. All of this is done through query parameters in the URL.

https://www.youtube.com/watch?v=8fADE16qXZk&feature=youtu.be

**Comment by timthelion** [comment]
Also, some old commits that were lost when merging master and devel are included. I think you forgot to pull from github before rebasing.

**Comment by timthelion** [comment]
Also, this increases test coverage by 1.45% !

**Comment by timthelion** [comment]
Iframe submit is a new view, it is purely optional.

20. ledna 2020 21:33:46 SEČ, Garret Wassermann <notifications@github.com> napsal:

**Pull request merged**
