### PR TITLE
Display a Total row in Reports

### PR DESCRIPTION
**Pull request by Benbb96**
image

### CODE REVIEW

**Comment by Benbb96** [comment]
Hi @gwasser,

I'm willing to participate to [Hacktoberfest](https://hacktoberfest.digitalocean.com/) this month. I plan to prepare some pull request with features I've done on my fork (such as the HTML Fields).

Is it possible to add "_hacktoberfest_" as a topic for this repository in order to let it be eligible for the event ?

**Comment by gwasser** [comment]
Thank you @Benbb96! I don't know how hacktoberfest works but I did add the topic to the repo if that helps. I'd say that folks should hack on the `master` branch to finally fix up the 0.3.x release if there's interest in that! If so, please join the #878 ticket to discuss what needs done.

**Comment by gwasser** [comment]
The travisci checks failed on this, just one test about report data violating permissions. Could you check this out and sort it out? Maybe the test needs updated. Thanks!

**Comment by gwasser** [comment]
Thank you! I'll apply the patch to `master` too so its upstream.

**Comment by Benbb96** [comment]
Thanks @gwasser !

I will comment on #878 to let know what I'm planning to do this month for Hacktober 😉

**Pull request merged**
