### PR TITLE
Django 4 support.

### PR DESCRIPTION
**Pull request by nickmccullum**

### CODE REVIEW

**Comment by gwasser** [comment]
Thank you so much for this! I think the best way to proceed is to actually rebase and merge this into the `unstable` branch for the 0.4 release. My thinking is that the current 0.3 release supports Django 2.2 -> 3.2. Some of the syntax changes here might break the Django 2.2 support, so instead let's do a 0.4 release that supports Django 3.2 -> 4.2 (when 4.2 LTS comes out) so that users have a nice upgrade path. I'd be ok with doing a 0.4 release sooner rather than later, with less new features, to focus on bugfixes and just getting something that supports Django 4 out the door. Then we can use the 0.5 release for more new features.

**Comment by nickmccullum** [comment]
Yes, that gameplan looks good to me!

**Review by Benbb96 — APPROVED** [review]

**Comment by nickmccullum** [comment]
Any update on this PR @gwasser

**Comment by gwasser** [comment]
@nickmccullum there's another PR coming in to add in a simple API, once that's merged early next week I'll merge this one in too so it's all compatible. Thanks!

**Comment by gwasser** [comment]
This was merged in but I haven't really tested `unstable` yet so appreciate  some help testing.

**Comment by nickmccullum** [comment]
It's working well on our end!

**Pull request merged**
