### PR TITLE
Fixes for my-tickets view and public ticket view

### PR DESCRIPTION
**Pull request by timthelion**
We didn't set the secret key in the urls in the my_tickets view so it wasn't possible to actually comment on tickets visited from this view.

### CODE REVIEW

**Comment by timthelion** [comment]
You have to merge the other two PRs I submitted before this one...

**Comment by timthelion** [comment]
@tecbr Fixed I hope.

**Review by uhurusurfa — APPROVED** [review]
👍 - looks good

**Comment by uhurusurfa** [comment]
@timthelion - if you want to release the webhooks enhancement and the my tickets bugfix asa new release then please raise a PR with the the "version" parameter changed to 1.2.0 in setup.py

**Pull request merged**
