### PR TITLE
New Checklist feature

### LINKED ISSUE #1087: Check List Option
Coming from the Spiceworks Helpdesk platform we were used to using the Checklist addon feature for managing onboard and offboarding staff. HR would raise a ticket; we would add the appropriate checklist and then complete each item as and when necessary. This allowed us to see what still needed doing and we could use it to confirm back to HR that procedures had been followed. I was wondering if this had ever been considered or if there was something similar that I have missed?

Thanks in advance.

### PR DESCRIPTION
**Pull request by Benbb96**
Fixes #1087

### CODE REVIEW

**Comment by Benbb96** [comment]
I've recorded [a video](https://youtu.be/wooqpaUe3bA) of me testing what I have implemented for checklists. I believe it's easier to see it instead of too much screenshots. But I'm thinking of deploying a demo site (with Render or PythonAnywhere) in order to better test features.

I'm willing to write more test but I'm looking forward for your feedback 😃

**Review by uhurusurfa — APPROVED** [review]
🚀  Awesome - really nice job with a comprehensive set of unit tests that makes it a lot easier to trust this PR. We can update the documentation in separate PR's and then release this as a new full version release shortly.

**Comment by uhurusurfa** [comment]
There is always more one can do around unit tests but it looks like you have the key stuff covered.
We can add more if and when issues arise to cover anything that may have been missed.
@brucegibbins - how does this look to you as a first step? More functionality can be added in separate PR's as needed.

**Comment by Benbb96** [comment]
Thank you @uhurusurfa ! Yes I think I'm done with the tests, they should cover the main part of added code. I can now work on a different PR in order to add documentation about this new feature.

While coding it, I noticed a lot of pages that need reformatting, or some views that need to be refactored. I may also work on this if I get time 🙂

**Comment by brucegibbins** [comment]
I agree. Fantastic job @Benbb96. The videos look great. I will take a
better look over the next few days. But it seems to look good so far in
meeting the brief.

**Comment by brucegibbins** [comment]
I have deployed your feature to our production instance. Does the job.
Thanks again.

**Comment by brucegibbins** [comment]
Thanks. The drag and mive is a nice feature in the task list.

I must admit to not being a big fan of the larger than life buttons that
the whole helpdesk package uses and some of the padding and alignment
around them. Just seems to be a lot of white space and gaps around things.
Not your solution specifically but just around the content in general. The
ticket list and view forms in particular.

Its one of the areas I'd like to improve but I'm not much of a front end ui
coder. But it is on my radar.

Again. Thanks for your help

**Comment by Benbb96** [comment]
Yes, I see your point, and part of it comes from the Bootstrap Framework. But I agree, there are a lot of improvements in terms of UI Design.

I think I can help with that too! We should create issues with screenshots of what could be fixed in order to track all these enhancements 🙂

**Comment by brucegibbins** [comment]
I'm up for that as well. Although I'm not much of a front end web
developer. I guess we raise a separate Issue and then go from there? I did
try to put some front end changes in play in my original fork but ended up
reversing them out as it broke some other things. One thing I would like to
do is simplify the header area of the ticket View. IMHO it is too  bulky
with a big heavy table upfront with too much padding and I spend a stack of
time scrolling past it.

My initial changes were to basically have foldable sections but I must have
mashed up a </div> as it ended up breaking and again to be honest the HTML
in that page is quite dense and not easily manipulated. Again, just my
opinion.

cheers

**Comment by Benbb96** [comment]
I agree with you on that point too. Having collapsible panels could be a solution, or maybe tabs. I'll create an issue for this 😉

**Pull request merged**
