### PR TITLE
Fix Few Bugs and Update Mail Handling

### PR DESCRIPTION
**Pull request by gwasser**
Grouped a few tasks into one PR:

Addressed #72 by basically commenting out Django tags with a simple search. Not a perfect solution, but it works since I think we really only want to give commenters the ability to access ticket/queue data, and that's it.

Addressed #184 by adding the suggested SQL to the install.rst file in docs/.

Implemented #95, which looks for CC'd addresses in the email headers, and adds them to the Ticket with view permissions. Also updated tests to handle CCs.

Also small tweak to Travis CI: Django 1.11 was released recently so might as well start testing against it! My understanding is that the Django 1.8 -> 1.11 shouldn't be a problem.

### CODE REVIEW

**Comment by gwasser** [comment]
Hey @reduxionist thanks for the review! Completely slipped my mind that the DB doesn't enforce uniqueness, was thinking it already did somehow.

Reworked it to get a list of currently CC'd emails and compare to CCs in new email, and only add the actual no ones, to prevent duplicates. Extended the test case with some duplicate CC emails to ensure that the duplicates really are left out (they are).

**Comment by gwasser** [comment]
Ok should be ready for review again. Thanks!

**Comment by gwasser** [comment]
I think I get what you're saying: one of the CC'd emails could be a helpdesk staff/user and so want to make sure that user isn't duplicated in CC?

**Comment by reduxionist** [comment]
Yes I think so: a staff member who is already subscribed to the ticket, because they are submitter or owner for example, should not get added as a CC just because they happen to have been CC'd on the message we're processing.

**Comment by gwasser** [comment]
Thanks for the feedback again @reduxionist ! Modified get_email and its test to now detect Users when they are CC'd on emails, and add the User as a CC rather than their email only if they aren't already CC'd or the Assignee or Submitter.

**Comment by gwasser** [comment]
OK It's ready for review again after some PEP-8 fixes (I should have just run it locally but I kept thinking I for sure had it :-) )

**Comment by reduxionist** [comment]
It was a nice collection of bug fixes from the start, but I want to thank you explicitly for the patience and persistence you gave to bugs I only described in theory, that was some top-notch professionalism and dedication on your part Mr. @gwasser Sir! 🎖

**Comment by gwasser** [comment]
Thanks @reduxionist ! Your reviews helped a lot. While I think the tests for get_email I added here were sufficient, I plan on cleaning them up and adding some more for improved coverage next in a new PR.

**Pull request merged**
