### PR TITLE
PY3 support and msgNum error solved in process_queue method

### PR DESCRIPTION
**Pull request by pawelmarkowski**

### CODE REVIEW

**Comment by pawelmarkowski** [comment]
In my case type of msg variable is <class 'bytes'>. Python 3.4 / django 1.10.4  (imap connection)

**Comment by reduxionist** [comment]
Thanks for PR, so as not to duplicate any efforts, I would check against #463 which refactors this code path and establishes some test coverage over. I have also included your commit fixing the blank title bug on a rebased version of PR393 currently queued up on my personal fork. 😄

**Comment by pawelmarkowski** [comment]
Great, so I am waiting for your upgrade.

In my opinion there is some kind of bug. If queue.slug does not match matchobj = re.match(r".*\[" + queue.slug + "-(?P<id>\d+)\]", subject)  get_email will create new ticket even if received message was an update for other queue.

**Comment by reduxionist** [comment]
As this PR was also effectively merged by #463, I'm closing it too. Thanks for all the contributions you've made @pawelmarkowski! 🏅  Please keep 'em coming! 😀

**Pull request closed without merging**
