### PR TITLE
Fix several bugs

### PR DESCRIPTION
**Pull request by gwasser**
Small bug fixes to several tickets for 0.2 milestone. See the commit messages.

### CODE REVIEW

**Comment by gwasser** [comment]
Oops forgot to run a PEP8 check and didn't realize check failed.

**Comment by gwasser** [comment]
To be more specific, this PR has fixes for: #502, #511, #525, #530

**Comment by gwasser** [comment]
@reduxionist @flinz any thoughts on this? any work in progress? if you're busy I'm happy to take on lead maintainer role and work on getting 0.2 out the door soon, but didn't want to just start merging without review and step on toes. thanks for all your support so far.

**Comment by reduxionist** [comment]
Nice clean work @gwasser! I apologize for not having been involved as of late, you definitely own the lead maintainer role now! :smile: I still hope to have the time to contribute here again soon, but I will transfer any lead privileges I may have over to you immediately -- thank you very much for keeping this project growing along healthily... :1st_place_medal:

**Comment by gwasser** [comment]
Thanks! I certainly understand pressure of time commitments, etc. Thanks for all your help so far @reduxionist and hope you are able to contribute in near future! I'll do my best to keep project growing well.

**Pull request merged**
