### PR TITLE
Disable timeline on ticket list

### PR DESCRIPTION
**Pull request by Mte90**
As per title, PR very simple but disable the timeline to simplify the interface

### CODE REVIEW

**Comment by timthelion** [comment]
It is possible to over-ride templates in django by creating a new template in your project with the same name and making sure your template dirs are ordered properly. This gives you full control over the template's appearance. It is much cleaner to over-ride the template than to have endless options for customizing them. The disadvantage of over-riding the templates is that if context variables change, then your custom templates could break, but the maintenance burden of supporting a million SETTINGS is too great for this project.

**Review by Benbb96 — APPROVED** [review]

**Comment by Mte90** [comment]
> It is possible to over-ride templates in django by creating a new template in your project with the same name and making sure your template dirs are ordered properly. This gives you full control over the template's appearance. It is much cleaner to over-ride the template than to have endless options for customizing them. The disadvantage of over-riding the templates is that if context variables change, then your custom templates could break, but the maintenance burden of supporting a million SETTINGS is too great for this project.

Yes I had the same doubt, it wasn't clear to me how a setting is defined, I mean when it is the case to enable a setting to change something.

**Comment by gwasser** [comment]
A custom template could accomplish this same thing pretty easily, just copy the existing template and remove the stuff you don't want. We can create our own settings whenever it seems useful to do so. I don't mind a setting if it's a common request.

**Comment by gwasser** [comment]
The main thing is that any new settings should be properly documented in the `docs/` folder so that new users know how to use it and what it does. Could you add some documentation to this PR, @Mte90 ? Thanks!

**Comment by Mte90** [comment]
I will update asap with the docs stuff :-)

**Comment by Mte90** [comment]
Documentation updated :-)

**Pull request merged**
