### PR TITLE
Add URL schemes that are allowed within links

### PR DESCRIPTION
**Pull request by noobpk**
## ALLOWED_URL_SCHEMES

 Default: `('file', 'ftp', 'ftps', 'http', 'https', 'irc', 'mailto', 'sftp', 'ssh', 'tel', 'telnet', 'tftp', 'vnc', 'xmpp')`

Fix bug Stored XSS via Markdown at Description or Comment of Ticket
Disclosure: https://huntr.dev/bounties/be7f211d-4bfd-44fd-91e8-682329906fbd/

Payload: ``[XSS](javascript:alert(`document.domain`))``

Before fix: `<a href="javascript:alert(document.domain)">XSS</a>`
After fix: `<a href="alert(document.domain)">XSS</a>`

### CODE REVIEW

**Comment by noobpk** [comment]
The fix can be bypass by multiline. 
Payload 

```
[Bypass

Multiline]( javascript:alert(`1`))
```
I'm looking for a way to fix regexes.
If you have any ideas for this please suggest me.

**Comment by noobpk** [comment]
Update new pattern : `fr'([\[\s\S\]]*?)\((?!({schemes})).*:(.+)\)'`

**Review by gwasser — APPROVED** [review]
Sounds good. I see you pushed a few additional commits, do you have anything else or is this ready to merge? thanks!

**Comment by noobpk** [comment]
> Sounds good. I see you pushed a few additional commits, do you have anything else or is this ready to merge? thanks!

yes, it is ready to merge. ^^!.

**Pull request merged**
