### PR TITLE
Basic support for tracking time spent on tickets and follow-ups

### PR DESCRIPTION
**Pull request by jachym**
Adding basic support for tracking spend time on tickets.

### CODE REVIEW

**Comment by timthelion** [comment]
Linguistically would have been better to use the phrase "Time spent" rather than "Time spend" but other than that it is a pretty simple change.

**Comment by jachym** [comment]
will continue on this pr, and will fix this, thanks for pointing me at it

**Comment by gwasser** [comment]
Sounds good! I agree "time spent" sounds better to me. Let me know when you're ready for a review and pull.

**Comment by jachym** [comment]
I have 2 issues:

1. I'm probably not able to implement any reasonable reports right now
2. Not sure, how to render proper time i the list of tickets. Serializer seems to support DurationField but the result is number of seconds (no really readable).

Otherwise, I do not have much to be added right now.

**Comment by jachym** [comment]
I've added also `dedicated_time` attribute to the `Queue` model.

@gwasser: what needs to be fixed in order to get this pull request merged?

**Comment by gwasser** [comment]
Looks good to me! Just make sure all the tests pass and add some new ones for new features. Make sure you fit the PEP8 style guide too, that looks to be the reason it didn't pass tests yet. Once the tests are all good I'll merge it in. Thanks!

**Comment by jachym** [comment]
@gwasser I've added some new tests and hope, it looks ok now.

**Pull request merged**
