### PR TITLE
Ticket has illegible file attachements from email

### PR DESCRIPTION
**Pull request by pawelmarkowski**
regarding #466

### CODE REVIEW

**Comment by pawelmarkowski** [comment]
TODO: fix python2.7 coding issue (probably add unicode mark)

**Comment by reduxionist** [comment]
Pawel, did you reference the branch on my fork that addressed this issue? Here we seem to be revertinf to an approach we've tried in the past but shich can't work for both py3 and py2. By using dfferent methods of the multi-part message class we can selectively attach as content (good for py2 where there's no penty for treating bytes as strings if the encodings work out) or we can attach as just pathon-dsk which is good for py3 since te std lib will handle the codec operations itself when it needs to). Sorry for typos on my phone... :wink:

**Comment by gwasser** [comment]
I've run into this problem before and thought it was fixed previously :-) it's definitely an encoding issue, and needs to be written so that it works on py2 and py3 (likely needs to use six support?) as encoding handling is vastly different between python 2 & 3. Thanks for starting the work @pawelmarkowski !

**Comment by pawelmarkowski** [comment]
@reduxionist Regarding your firt question - yes, I did.  I fetched your branch and after couple changes and  few tests I merged it and deleted. I think there is a chance to add for example:
@python_2_unicode_compatible

and add: part_attachment.add_header('Content-Disposition', **u**'attachment; filename="{}"'.format(file_name)) symbol. Unfortunately I do not have a possibility to make a tests in py 2.7 

I have seen six.PY3 condition in your code. I thought that the message was not attached due a mimetype and headers that were missing so I changed this part of code too.

**Comment by tshabs** [comment]
I have tested this on Python 3.4.2 w/ Django version 1.9.1 and it solves the issue for me.   Thanks.

**Comment by reduxionist** [comment]
Thanks for the review @tshabs! 😄 

Although @pawelmarkowski's  excellent combined-and-refined patch also LGTM as the solution to this issue, unfortunately it fails to build for Django 1.8 under Py3. The issue is that Django's re-implementation of the standard library's email module complicates Py2/3 compatibility, but they didn't revert back to the standard lib's version until Django 1.9. 💢 

Since there's still another three months before Django's next LTS release, I don't feel we can make our support for 1.8 a Py2-only option just yet... Having taken a few swings at this already myself, the simplest solution I can come up with for now is to split out our 1.8/Py3 support into a separate branch until they release 1.11 this spring.  It's just the templated outbound-mail that needs this special handling, so I'm fine volunteering to handle any dual-patching maintenance-overhead that this might incur. Any thoughts from the maintainer's gallery @flinz, @gwasser et al.?

**Comment by gwasser** [comment]
Hmm, complex situation. I guess my concern is how users will know to use a special branch until then? I appreciate you volunteering to upkeep the separate branch! I'm fine with that as long as we have a bug report or wiki saying to use that branch until 1.11 is out.

I think when 1.11 is out, it would be fair to branch off the 0.2.0 release separately, and have master target 1.11+ (as a 0.3.0 I guess?). So that's longer term solution.

**Comment by pawelmarkowski** [comment]
are you sure is it a problem with lib not with the tests? Can anybody check it under django 1.8? Unfortunately I do not have enough time in next 2-3 weeks.

**Comment by gwasser** [comment]
I merged in the patch now that Django 1.11 is out. We'll switch to 1.11 as the minimum required version, since 1.11 will not remove any features of 1.8-1.10 but fixed the mail handling issues in 1.8 that caused trouble here.

**Pull request merged**
