### PR TITLE
Create user by REST endpoint

### PR DESCRIPTION
**Pull request by Mte90**
It's the first time that I work with them but I was able to create an endpoint that works. 

I am not sure about naming convention and so on but works :-)

### CODE REVIEW

**Comment by timthelion** [comment]
Is there some kind of permissions check?

**Comment by Mte90** [comment]
I was thinking that all the rest endpoints there require the token so also this one.  
I used the web interface on http://127.0.0.1:8080/api/users/ that allows just POST.

**Comment by gwasser** [comment]
Thanks! I mostly want to make sure we consider security here. Is this a necessary thing for the API? Should the admin log into the admin panel to create users instead?

**Comment by timthelion** [comment]
The other thing that occures to me is that this isn't a helpdesk specific task so might fit better somewhere not in the helpdesk code...

**Comment by Mte90** [comment]
I will update the PR with that change.

About the implementation usually ticket platforms have this so you can create it.

**Comment by gwasser** [comment]
@Mte90 merged! I will likely wrap this up into the next release this weekend when I have a little more time. thank you for your work on this!

**Pull request merged**
