### PR TITLE
Sidebar bookmarks, closes  #1175

### LINKED ISSUE #1175: Configurable list of bookmarks in sidebar menu
**Is your feature request related to a problem? Please describe.**

- When integrating django-helpdesk into an existing Django project one can 'enter' the helpdesk, but not 'leave' -
  navigate back to other apps in the project.
- In a helpdesk environment it is helpful provide the personnel with links to related applications or sites.

**Describe the solution you'd like**

A configurable list of "bookmarks" in the sidebar menu, which is clearly separated from the django-helpdesk menu entries.
This bookmarks section must not show, when no bookmarks are configured.

**Describe alternatives you've considered**

None

**Additional context**

PR is following

### PR DESCRIPTION
**Pull request by jorge-leon**
This PR adds a configuration setting:

     HELPDESK_BOOKMARKS

When set to a list of 'bookmarks', an additional section is shown on the sidebar menu, rendering the bookmarks.

There are two types of bookmarks:

- internal: given as names to resolve by the `reverse()` method of the URL dispatcher
- external: given as URLs.

They are rendered differently so the user can distinguish if she will stay in the Django project or leave to another site.

A bookmark is specified in the following way:
- internal: `{ 'name': `_internal_name_`, 'label': `_label_ }`
- external: `{ 'URL': `_external_url_`, 'label': `_label_ }`

The `label` is the link text. It is optional, if not given the `name` or `URL` is used instead.

### CODE REVIEW

**Comment by timthelion** [comment]
I personally would prefer to add sections to the django template if needed so that you can simply over-ride and reimport the the template than to have a new setting for this.

**Comment by jorge-leon** [comment]
> I personally would prefer to add sections to the django template if needed so that you can simply over-ride and reimport the the template than to have a new setting for this.

Can you elaborate on this. I'll consider doing the respective changes when I know how to do it. Maybe there is an example you can point me to.

**Comment by Benbb96** [comment]
Yes I think documentation could be better explained on [this page](https://django-helpdesk.readthedocs.io/en/v1.2.0/custom_templates.html), maybe with an example like overriding the sidebar.

Following [Django documentation](https://docs.djangoproject.com/en/stable/howto/overriding-templates/#extending-an-overridden-template), we could add custom blocks in _django-helpdesk_ templates in order to avoid too much copy-pasting when overriding a file.

**Comment by timthelion** [comment]
@jorge-leon 

To do this you would rename https://github.com/django-helpdesk/django-helpdesk/blob/main/helpdesk/templates/helpdesk/navigation-sidebar.html to navigation-sidebar-base.html you can then add blocks like so https://github.com/django-helpdesk/django-helpdesk/blob/dce3c0c73f3a304118d62c9affdee1c73ba608e7/helpdesk/templates/helpdesk/base.html#L48 where you want to insert things into the sidebar.

Then you would add a new `navigation-sidebar.html` file which uses an extends line like this https://github.com/django-helpdesk/django-helpdesk/tree/main/helpdesk/templates/helpdesk

Then you would create a PR to this repo.

After that, you can add a template file to the appropriate directory to override `navigation-sidebar.html`. Here is an example path for where you would place a file to over-ride a template:

https://github.com/django-helpdesk/django-helpdesk/blob/dce3c0c73f3a304118d62c9affdee1c73ba608e7/standalone/docker-compose.yml#L21

**Comment by uhurusurfa** [comment]
@jorge-leon Is this still a work in progress or ready for review?

**Comment by jorge-leon** [comment]
> @jorge-leon Is this still a work in progress or ready for review?

Now that the other PR's are done, I will work on this one.
However it will be a completely different implementation.  So it would also be ok to just close this PR without merging until I work out the other approach.

**Comment by uhurusurfa** [comment]
> > @jorge-leon Is this still a work in progress or ready for review?
> 
> Now that the other PR's are done, I will work on this one. However it will be a completely different implementation. So it would also be ok to just close this PR without merging until I work out the other approach.

Yes go ahead.
Note that now thatr you are a team collaborator you can raise PR's within this project instead of a cloned version.

**Comment by uhurusurfa** [comment]
@jorge-leon Just to confirm that we should close this PR as you will raise a different one to accomplish a similar bit of functionality?

**Pull request closed without merging**
