### PR TITLE
Remove azure and default to pull requests,opened/reopened

### PR DESCRIPTION
**Pull request by martin-marty**
Should now run github workflows on PRs

### CODE REVIEW

**Review by gwasser — APPROVED** [review]

**Comment by gwasser** [comment]
I'm assuming the "waiting" status is azure and we don't need to wait for it to merge?

**Review by uhurusurfa — APPROVED** [review]
👍 - looks good - we can now ad some other checks in

**Comment by uhurusurfa** [comment]
> I'm assuming the "waiting" status is azure and we don't need to wait for it to merge?

@gwasser - I have a feeling iot is something in the settings for the project but we do not have access to the settings to figure it out.

**Comment by gwasser** [comment]
Yes I think I know where I probably made it a requirement. I'll merge this and tweak the settings. Thanks!

**Pull request merged**
