### PR TITLE
Add user threading feature - issue #375

### PR DESCRIPTION
**Pull request by brunotikami**
Hello,

I'd like you to have  a look at my approach to enable user threading to your tool. Please feel free to request changes and question this PR.

Keep up the good work,

Tkm

### CODE REVIEW

**Comment by rossp** [comment]
Can you please give us a few particular pointers here - there is a huge amount of change in this PR and manually reviewing files to try to get the gist of what it's meant to do.

**Comment by brunotikami** [comment]
Sure, no problem!

The changes:

- the TicketCCForm to overwrite the <clean> method so we can check if either a valid user or an email is provided.

- the <send_templated_mail> function from the libs module to accept extra headers so "In-Reply-To" can be specified

- I've added the "message_id" field to the FollowUp model to enable mail threading / tracking and the migration 0012 to support this

- the <subscribe_staff_member_to_ticket> function from the views/staff module now uses a < subscribe_to_ticket_updates>. The new method allow subscribing without a User instance if you have a valid email

- tests for a big part of this operations

- the big change: management.commands.get_email may create either a new Ticket or a FollowUp from one mail message:

    -  If the "In-Reply-To" header is found on the database or if we can find the ticket ID applying the regexp on the email's subject, we will add this to the Ticket's thread.
    -  else, it's a new Ticket.

    After creating the right object, notifications are sent using the same templates that the Queue uses. Another feature is that any email on the Cc list from the mail message gets a TicketCC object linked to the Ticket.

**Comment by alexbarcelo** [comment]
You have some `print` statement that does not work on Python 3. The quickest fix should be performing the `from __future__ import print_function` and using the `print()` form.

I have not checked if there are extra python 3 problems --I have all my deployment in 2.7, so :-/

**Comment by brunotikami** [comment]
Hi @alexbarcelo, I didn't change these statements in order to avoid a PR that would touch various aspects of the code. Anyway, as I'll add an functionality to this PR, I'll change that too. 

Just so you and @rossp know, I'll add an extra field / flag to the Queue model to decide when to notify users when an email is processed.

**Comment by alexbarcelo** [comment]
Sorry, I saw the error in the tests and just assumed... I should have
checked.

Maybe it is better to prepare a different PR to fix those print statements
and other Python 3 stuff. To isolate different issues in different PR.

Ross, what do you think about that?

**Comment by brunotikami** [comment]
It turns out, @alexbarcelo, that the print statements are not the only things I'd need to change to get the project 3.x compatible. In a quick look I've found an backwards incompatible change of the email library (email.Utils is now called email.utils) and, of course, the unicode X bytes part. I'll open the separate PR for the print statements anyway :-)

**Comment by alexbarcelo** [comment]
Hey @brunotikami, are you still interested in this feature? I was very interested, but we had to drop the idea for a while because of some time constraints and overlapping project goals.

Now we wanted to resume the idea of mail integration and user threading, and just now I was looking the status on this. You started an awesome PR :+1: but I am not sure on the impact of the 0.2 branch on this.

**Comment by gwasser** [comment]
I merged this in manually to the `develop` branch for the 0.3 release. Thanks very much for the effort!

**Pull request closed without merging**
