### PR TITLE
Fix errors on master

### PR DESCRIPTION
**Pull request by Benbb96**
As part of my contribution for #878, here is my PR to fix errors I had on master.  
I've taken the opportunity to clean things up and remove useless imports (read commit history for more details).

I had to set an absolute path for `ROOT_URLCONF` and `WSGI_APPLICATION`in order to run my local server. I don't know if that could break things for others or the tests (which I still don't know how to run correctly).

### CODE REVIEW

**Comment by gwasser** [comment]
Tests are run with `python quicktest.py helpdesk`. It's a pretty old testing harness so I'd fully support modernizing it if feasible (although maybe we'll push that to the 0.4.x release simply to not hold up the 0.3.x any longer).

**Comment by gwasser** [comment]
There's a few interesting errors in the travis-ci testing here. Some of the template tags are crashing for not being "iterable". Other than that looks like maybe the `get_email.py` script doesn't have the right imports or something.

**Comment by gwasser** [comment]
I merged the bugfixes from the not yet released 0.2.23 bug fix release into `master`, please do a pull and check that your PR syncs with latest `master`! sorry if this caused you some trouble.

**Comment by Benbb96** [comment]
No problem, I think I'll do it today.

**Pull request merged**
