### PR TITLE
Small bug fixes (ticket and followup title display, vote function)

### PR DESCRIPTION
**Pull request by samsplunks**
By testing the application, a friend of mine has found a few bugs and here is a proposal to fix them.

### CODE REVIEW

**Comment by uhurusurfa** [comment]
@samsplunks - whilst you are working on this, can you please change this line in setup.py
`version = '1.2.0'`
TO:
`version = '1.3.0'`

There are a bunch of enhancements and achanges that need to be released into a new version which we will do once this PR is merged.

**Comment by samsplunks** [comment]
I will!

```
# temporary pastebin
<form method="post" action="{% url "helpdesk:kb_vote" item.pk "up" %}" style="display: inline">{% csrf_token %}
                    <button type="submit" class="btn btn-success btn-circle btn-xl"><i class="fa fa-thumbs-up fa-lg"></i></button></form>
<form method="post" action="{% url "helpdesk:kb_vote" item.pk "down" %}" style="display: inline">{% csrf_token %}
                    <button type="submit" class="btn btn-danger btn-circle btn-xl"><i class="fa fa-thumbs-down fa-lg"></i></submit></form>
```

**Comment by samsplunks** [comment]
All good on my side.

**Review by uhurusurfa — APPROVED** [review]
👍  confirmed I cannot manually reproduce the vulnerabilities with the PR branch.

Thanks for the fix.

**Pull request merged**
