### PR TITLE
Set version to 0.2.0, remove Django 1.7 from requirements and testing

### PR DESCRIPTION
**Pull request by gwasser**
As discussed in #433 and #420, removing out-of-support Django 1.7 from latest branch. Setting version to 0.2.0.

I suggest merging this one in, then any other milestone 0.2 PRs. Then making a 0.2.0 official release and tag it (possibly on a new 0.2 branch for further development?).

### CODE REVIEW

**Comment by gwasser** [comment]
Did we go through all the old PRs? We should merge anything else small before we branch for 0.2 and merge this one.

**Comment by reduxionist** [comment]
I just checked the other PRs and @flinz had already given a helpful push forwards to any that were in a position to make progress. The others are waiting either for a response from contributor or for a 0.2 brach to move to! :)

**Comment by reduxionist** [comment]
I failed to notice that #438 was based on the branch you started here, and so, mistakenly thinking I'd merged this already due to the lack of conflicts, I merged #438 first and thus your commits were added via that PR instead of this one. 😳 My sincere apologies for the out-of-order screw up! 🙇

**Comment by alexbarcelo** [comment]
First of all I should apologize for doing strange things sometimes in PR --my fault. However, I don't recall having #438 base on this one (I remember messing a little bit, from lazyness, on #374, which is based on #438, but #438 was intended to be based on master).

I was checking and master seems to not have the 0.2 changes yet. So this branch can be merged, I think.

**Comment by reduxionist** [comment]
Nothing to apologize for @alexbarcelo, it's entirely my fault! I was doubly mistaken, but thanks to your correction I think I found the root error: somehow I managed to swap the ID numbers used as branch names for the PRs I was pulling to local while testing what order to merge them in. 😩

**Comment by reduxionist** [comment]
Sorry again for complicating a simple merge, my apologies for all the noise, and thanks for all your efforts! 😅

**Pull request merged**
