### PR TITLE
Remove Unused Dependency: Simplejson

### PR DESCRIPTION
**Pull request by gdrosos**
## Summary

This pull request removes the unused dependency `simplejson` from the `requirements.txt`  and `requirements-no-pinax.txt ` configuration files. The removal of this dependency is a finding from ongoing research aimed at identifying and eliminating code bloat within software projects.

## Rationale

The `simplejson` dependency was initially introduced in commit 61f49786c08ef4a4ff264ad63397a6f3c588921e and added to the `requirements.txt` file through commit a749726. However, the code invoking `simplejson` was marked as deprecated and later removed in [this pull request](https://github.com/django-helpdesk/django-helpdesk/pull/441), rendering the dependency unnecessary. Despite its removal from the source code, `simplejson` remained listed as a requirement in the project's dependency files. Removing this unused dependenc  reduces the overall footprint of the application, mitigating potential security risks, and simplifying the dependency management process.

## Changes

- Removed the `simplejson` dependency from the `requirements.txt` file.
- Removed the `simplejson` dependency from the `requirements-no-pinax.txt` file.

## Impact

- **Reduced Package Size**: The removal of this unused dependency will lead to a decrease in the overall size of the installed packages.
- **Simplified Dependency Tree**: Fewer dependencies make the project easier to maintain and can speed up installation.

### CODE REVIEW

**Review by Benbb96 — APPROVED** [review]
Good catch!

**Comment by gdrosos** [comment]
Τhanks @Benbb96  for the immediate response! I can also succesfully run the tests (using `make test`),
but for some reason the tests running though github actions fail.

**Comment by gdrosos** [comment]
Actually I 

> Indeed one test is failing: `test_ticket_field_autofill (helpdesk.tests.test_ticket_submission.EmailInteractionsTestCase)` and I can't see why for now. I tried to re-run tests just in case but I get the same result.

Thank you for looking into the test failure, @Benbb96. I took the initiative to further investigate the issue by running the `quicktest.py` on my local machine. Interestingly, I can reproduce the failure in `test_ticket_field_autofill (helpdesk.tests.test_ticket_submission.EmailInteractionsTestCase)` regardless of whether `simplejson` is included or not.

I ran the test both with and without the `simplejson` dependency, and the result was the same in both cases. This leads me to believe that the failure is unrelated to the changes made in this pull request.

Please let me know if there's anything else I can do to assist in resolving this issue or if there are any other concerns about the changes proposed in this PR.

**Comment by uhurusurfa** [comment]
There are quite a few flaky unit tests that are timing dependnet and this one may fall into that category.
There are 2 in #1104 and once that is merged I will take a look at what is causing this failure.

**Comment by gdrosos** [comment]
Hello @Benbb96  and @uhurusurfa,

I hope you're both well. I wanted to check in on the status of this pull request. If there are any remaining concerns or if you need further information from my end, please feel free to let me know. 

Thank you for your consideration!

**Comment by uhurusurfa** [comment]
Just waiting to get some fixes in for flaky unit tests as we cannot merge any PR that is not passing the unit tests and other checks that are part of the workflow.
I fixed some in a separate PR focussed on parsing emails but have yet to finalise that PR as the testing uncovers issues with the current PR.
Hopefully once that email parsing PR is merged, your PR will start to pass the tests.

**Pull request merged**
